#!/bin/bash
# ══════════════════════════════════════════════════════════════════════
# HELPIT AUTONOMOUS AGENT — macOS
# Version 2.0.0
# ══════════════════════════════════════════════════════════════════════
#
# Generated by the HelpIT portal with your session tokens embedded.
# Just run it — no login needed. Your browser will show live results.
#
# Double-click to run, or: chmod +x helpit-agent.command && ./helpit-agent.command
# ══════════════════════════════════════════════════════════════════════

# ── TOKENS (baked in by portal at download time) ───────────────────
HELPIT_API_BASE="https://agent.helpitinc.com"
AUTH_TOKEN="{{AUTH_TOKEN}}"
SESSION_ID="{{SESSION_ID}}"
SESSION_TOKEN="{{SESSION_TOKEN}}"
AGENT_VERSION="2.0.0"
POLL_INTERVAL=8

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; WHITE='\033[1;37m'; GRAY='\033[0;37m'; NC='\033[0m'

# ── DISPLAY HELPERS ────────────────────────────────────────────────

show_banner() {
    clear
    echo ""
    echo -e "  ${CYAN}╔══════════════════════════════════════════════╗${NC}"
    echo -e "  ${CYAN}║                                              ║${NC}"
    echo -e "  ${CYAN}║         HELPIT AUTONOMOUS TECHNICIAN         ║${NC}"
    echo -e "  ${CYAN}║                                              ║${NC}"
    echo -e "  ${CYAN}╚══════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${GREEN}Connected to HelpIT servers.${NC}"
    echo -e "  ${GRAY}Your browser will open with live results.${NC}"
    echo -e "  ${GRAY}You can minimize this window.${NC}"
    echo ""
}

show_status() { echo -e "  ${YELLOW}$1${NC}"; }
show_ok() { echo -e "  ${GREEN}[OK]${NC} $1"; }
show_fail() { echo -e "  ${RED}[!!]${NC} $1"; }

# ── API HELPER ─────────────────────────────────────────────────────

call_api() {
    local method="$1" path="$2" body="$3"
    local url="${HELPIT_API_BASE}${path}"
    local args=(-s -S -H "Content-Type: application/json" -H "Authorization: Bearer $AUTH_TOKEN")

    if [ "$method" = "GET" ]; then
        args+=(-X GET)
    elif [ "$method" = "POST" ]; then
        args+=(-X POST)
        [ -n "$body" ] && args+=(-d "$body")
    elif [ "$method" = "PATCH" ]; then
        args+=(-X PATCH)
        [ -n "$body" ] && args+=(-d "$body")
    fi

    curl "${args[@]}" "$url" 2>/dev/null
}

json_get_safe() {
    local json="$1" key="$2" default="$3"
    echo "$json" | python3 -c "
import sys,json
try:
    d=json.load(sys.stdin); val=d$key
    print(val if val is not None else '$default')
except: print('$default')
" 2>/dev/null || echo "$default"
}


# ══════════════════════════════════════════════════════════════════════
# STEP 1: OPEN PORTAL IN BROWSER
# ══════════════════════════════════════════════════════════════════════

open_portal() {
    local portal_url="${HELPIT_API_BASE}/helpit-agent/session/${SESSION_ID}"
    echo -e "  ${CYAN}Opening your HelpIT dashboard...${NC}"
    echo -e "  ${GRAY}View live results at:${NC}"
    echo -e "  ${YELLOW}$portal_url${NC}"
    echo ""
    open "$portal_url" 2>/dev/null || true
}


# ══════════════════════════════════════════════════════════════════════
# STEP 2: SCAN THE MAC
# ══════════════════════════════════════════════════════════════════════

run_scan() {
    show_status "Scanning your Mac..."

    call_api "PATCH" "/api/agent/session/$SESSION_ID" '{"status":"scanning"}' > /dev/null

    SCAN_DATA=$(python3 << 'PYEOF'
import json, subprocess, os, platform, time, socket

scan = {}

# OS
try:
    scan["os"] = {
        "name": subprocess.check_output(["sw_vers", "-productName"], text=True).strip(),
        "version": subprocess.check_output(["sw_vers", "-productVersion"], text=True).strip(),
        "build": subprocess.check_output(["sw_vers", "-buildVersion"], text=True).strip(),
        "architecture": platform.machine(),
    }
    boot = subprocess.check_output(["sysctl", "-n", "kern.boottime"], text=True)
    boot_sec = int(boot.split("sec = ")[1].split(",")[0])
    scan["os"]["uptime_hours"] = round((time.time() - boot_sec) / 3600, 1)
except Exception as e:
    scan["os"] = {"name": "macOS", "error": str(e)}

# Hardware
try:
    cpu = subprocess.check_output(["sysctl", "-n", "machdep.cpu.brand_string"], text=True).strip()
    mem_bytes = int(subprocess.check_output(["sysctl", "-n", "hw.memsize"], text=True).strip())
    mem_total_gb = round(mem_bytes / (1024**3), 1)
    vm = subprocess.check_output(["vm_stat"], text=True)
    pages_free = int([l for l in vm.split("\n") if "Pages free" in l][0].split(":")[1].strip().rstrip("."))
    pages_inactive = int([l for l in vm.split("\n") if "Pages inactive" in l][0].split(":")[1].strip().rstrip("."))
    available_gb = round((pages_free + pages_inactive) * 4096 / (1024**3), 1)
    df = subprocess.check_output(["df", "-g", "/"], text=True).split("\n")[1].split()
    scan["hardware"] = {
        "cpu": cpu, "ram_total_gb": mem_total_gb, "ram_available_gb": available_gb,
        "disk_total_gb": int(df[1]), "disk_free_gb": int(df[3]),
    }
except Exception as e:
    scan["hardware"] = {"error": str(e)}

# Security
try:
    fw = subprocess.check_output(["/usr/libexec/ApplicationFirewall/socketfilterfw", "--getglobalstate"], text=True)
    try:
        updates = subprocess.check_output(["softwareupdate", "-l", "--no-scan"], text=True, timeout=10)
        pending = updates.count("* Label:")
    except: pending = -1
    scan["security"] = {"antivirus": "macOS XProtect", "firewall_enabled": "enabled" in fw.lower(), "pending_updates": pending}
except Exception as e:
    scan["security"] = {"error": str(e)}

# Startup (Launch Agents)
try:
    agents = []
    for d in [os.path.expanduser("~/Library/LaunchAgents"), "/Library/LaunchAgents"]:
        if os.path.isdir(d):
            for f in os.listdir(d):
                if f.endswith(".plist"):
                    agents.append({"name": f.replace(".plist",""), "enabled": True, "impact": "medium"})
    scan["startup_programs"] = agents
except: scan["startup_programs"] = []

# Processes
try:
    ps = subprocess.check_output(["ps", "aux"], text=True)
    lines = ps.strip().split("\n")[1:]
    scan["running_processes"] = len(lines)
    top = subprocess.check_output(["ps", "aux", "--sort=-%mem"], text=True).split("\n")[1:11]
    top_procs = []
    for line in top:
        parts = line.split()
        if len(parts) > 10:
            top_procs.append({"name": parts[10].split("/")[-1], "memory_mb": round(float(parts[3]) * mem_total_gb * 1024 / 100, 0)})
    scan["top_processes"] = top_procs
except: scan["running_processes"] = 0

# Network
try:
    dns_working = True
    try: socket.getaddrinfo("www.google.com", 80)
    except: dns_working = False
    dns_out = subprocess.check_output(["scutil", "--dns"], text=True)
    dns_list = list(set([l.split(":")[1].strip() for l in dns_out.split("\n") if "nameserver" in l][:4]))
    scan["network"] = {"dns_working": dns_working, "dns": dns_list}
except: scan["network"] = {"dns_working": True}

# Cache/temp
try:
    cache_size = 0
    for d in [os.path.expanduser("~/Library/Caches"), "/tmp"]:
        if os.path.isdir(d):
            for root, dirs, files in os.walk(d):
                for f in files:
                    try: cache_size += os.path.getsize(os.path.join(root, f))
                    except: pass
    scan["temp_files_gb"] = round(cache_size / (1024**3), 2)
except: scan["temp_files_gb"] = 0

# Browser extensions
try:
    ext = 0
    for d in [os.path.expanduser("~/Library/Application Support/Google/Chrome/Default/Extensions"),
              os.path.expanduser("~/Library/Safari/Extensions")]:
        if os.path.isdir(d): ext += len(os.listdir(d))
    scan["browser_extensions"] = ext
except: scan["browser_extensions"] = 0

# Installed apps
try:
    scan["installed_programs_count"] = len([a for a in os.listdir("/Applications") if a.endswith(".app")])
except: scan["installed_programs_count"] = 0

print(json.dumps(scan))
PYEOF
)

    show_ok "Scan complete!"
}


# ══════════════════════════════════════════════════════════════════════
# STEP 3: SUBMIT TO AI
# ══════════════════════════════════════════════════════════════════════

submit_scan() {
    show_status "Sending to AI for analysis..."

    local body
    body=$(python3 -c "
import json
scan = json.loads('''$SCAN_DATA''')
print(json.dumps({'session_token': '$SESSION_TOKEN', 'scan_data': scan}))
")

    ANALYSIS_RESULT=$(call_api "POST" "/api/agent/scan" "$body")

    local ok
    ok=$(json_get_safe "$ANALYSIS_RESULT" "['ok']" "false")
    if [ "$ok" != "True" ] && [ "$ok" != "true" ]; then
        show_fail "AI analysis failed."
        return 1
    fi

    show_ok "Analysis complete. Check your browser for results."
    return 0
}


# ══════════════════════════════════════════════════════════════════════
# STEP 4: WAIT FOR APPROVAL
# ══════════════════════════════════════════════════════════════════════

wait_for_approval() {
    show_status "Waiting for you to approve fixes in the browser..."
    echo -e "  ${GRAY}(You can minimize this window)${NC}"

    local elapsed=0 max_wait=600
    while [ $elapsed -lt $max_wait ]; do
        sleep $POLL_INTERVAL
        elapsed=$((elapsed + POLL_INTERVAL))

        local session_data
        session_data=$(call_api "GET" "/api/agent/session/$SESSION_ID")
        local status
        status=$(json_get_safe "$session_data" "['session']['status']" "")

        if [ "$status" = "fixing" ]; then
            show_ok "Fixes approved! Applying now..."
            APPROVED_FIXES="$session_data"
            return 0
        elif [ "$status" = "cancelled" ]; then
            show_status "Session cancelled. No changes made."
            return 1
        fi
    done

    show_fail "Timed out (10 minutes)."
    return 1
}


# ══════════════════════════════════════════════════════════════════════
# STEP 5: APPLY FIXES
# ══════════════════════════════════════════════════════════════════════

apply_fixes() {
    show_status "Applying fixes..."

    # Time Machine snapshot
    tmutil localsnapshot / 2>/dev/null && show_ok "Safety snapshot created." || true

    python3 << PYEOF
import json, subprocess, sys

try:
    data = json.loads('''$(echo "$APPROVED_FIXES" | sed "s/'/\\\\'/g")''')
    fixes = data.get("session", {}).get("fixes_approved", [])
    if not fixes:
        print("  No fixes to apply.")
        sys.exit(0)

    total = len(fixes)
    for i, fix in enumerate(fixes, 1):
        title = fix.get("title", "Unknown")
        fix_info = fix.get("fix", {})
        command = fix_info.get("command", "")
        description = fix_info.get("description", "")

        print(f"  [{i}/{total}] {title}")
        result = "success"
        error_details = None

        if command:
            try:
                output = subprocess.run(command, shell=True, capture_output=True, text=True, timeout=120)
                if output.returncode == 0:
                    print(f"  \033[0;32m[OK]\033[0m {description}")
                else:
                    result = "failed"
                    error_details = output.stderr[:200] if output.stderr else "Non-zero exit"
                    print(f"  \033[0;31m[!!]\033[0m {error_details}")
            except subprocess.TimeoutExpired:
                result = "failed"; error_details = "Timed out"
                print(f"  \033[0;31m[!!]\033[0m Timed out")
            except Exception as e:
                result = "failed"; error_details = str(e)
                print(f"  \033[0;31m[!!]\033[0m {e}")
        else:
            print(f"  \033[0;32m[OK]\033[0m Noted in report")

        import urllib.request
        body = json.dumps({"session_token":"$SESSION_TOKEN","fix_id":title,"result":result,"error_details":error_details}).encode()
        req = urllib.request.Request("${HELPIT_API_BASE}/api/agent/fix-result", data=body,
            headers={"Content-Type":"application/json","Authorization":"Bearer $AUTH_TOKEN"}, method="POST")
        try: urllib.request.urlopen(req, timeout=10)
        except: pass

except Exception as e:
    print(f"  Error: {e}", file=sys.stderr)
PYEOF
}


# ══════════════════════════════════════════════════════════════════════
# STEP 6: CLEANUP
# ══════════════════════════════════════════════════════════════════════

cleanup() {
    echo ""
    echo -e "  ${GREEN}All done! Check your browser for the full report.${NC}"
    echo -e "  ${GRAY}This window will close in 10 seconds.${NC}"
    sleep 10

    local script_path
    script_path="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
    (sleep 3 && rm -f "$script_path") &
}


# ══════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════

main() {
    show_banner
    open_portal
    run_scan

    if ! submit_scan; then
        call_api "PATCH" "/api/agent/session/$SESSION_ID" '{"status":"failed","error_message":"AI analysis failed"}' > /dev/null
        sleep 5; exit 1
    fi

    local issue_count
    issue_count=$(json_get_safe "$ANALYSIS_RESULT" "['analysis']['issueCount']" "0")
    if [ "$issue_count" = "0" ]; then
        show_ok "No issues found! Your Mac is healthy."
        cleanup; exit 0
    fi

    if ! wait_for_approval; then exit 0; fi
    apply_fixes
    cleanup
}

main "$@"
