# ══════════════════════════════════════════════════════════════════════
# HELPIT AUTONOMOUS AGENT — Windows
# Version 2.0.0
# ══════════════════════════════════════════════════════════════════════
#
# This script is generated by the HelpIT portal with your session
# tokens already embedded. Just run it — no login needed.
#
# RIGHT-CLICK → "Run with PowerShell"
# ══════════════════════════════════════════════════════════════════════

# ── TOKENS (baked in by portal at download time) ───────────────────
# Your Anything.com backend replaces these placeholders when the
# customer clicks "Download for Windows" on the portal.

$HELPIT_API_BASE = "https://agent.helpitinc.com"
$AUTH_TOKEN = "{{AUTH_TOKEN}}"
$SESSION_ID = "{{SESSION_ID}}"
$SESSION_TOKEN = "{{SESSION_TOKEN}}"
$AGENT_VERSION = "2.0.0"
$POLL_INTERVAL = 8

# ── DISPLAY HELPERS ────────────────────────────────────────────────

function Show-Banner {
    Clear-Host
    Write-Host ""
    Write-Host "  ╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "  ║                                              ║" -ForegroundColor Cyan
    Write-Host "  ║         HELPIT AUTONOMOUS TECHNICIAN         ║" -ForegroundColor Cyan
    Write-Host "  ║                                              ║" -ForegroundColor Cyan
    Write-Host "  ╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Connected to HelpIT servers." -ForegroundColor Green
    Write-Host "  Your browser will open with live results." -ForegroundColor Gray
    Write-Host "  You can minimize this window." -ForegroundColor DarkGray
    Write-Host ""
}

function Show-Status {
    param([string]$Msg, [string]$Color = "Yellow")
    Write-Host "  $Msg" -ForegroundColor $Color
}

function Show-Progress {
    param([string]$Label, [int]$Pct)
    $filled = [math]::Floor(30 * $Pct / 100)
    $bar = ("█" * $filled) + ("░" * (30 - $filled))
    Write-Host "`r  [$bar] $Pct% $Label    " -NoNewline -ForegroundColor Yellow
}

function Call-API {
    param([string]$Method, [string]$Path, [hashtable]$Body = $null)
    $uri = "$HELPIT_API_BASE$Path"
    $headers = @{
        "Content-Type"  = "application/json"
        "Authorization" = "Bearer $AUTH_TOKEN"
    }
    $params = @{ Uri = $uri; Method = $Method; Headers = $headers }
    if ($Body) { $params["Body"] = ($Body | ConvertTo-Json -Depth 10 -Compress) }

    try {
        return Invoke-RestMethod @params -TimeoutSec 60
    } catch {
        return @{ "_error" = $true; "message" = $_.Exception.Message }
    }
}


# ══════════════════════════════════════════════════════════════════════
# STEP 1: OPEN PORTAL SESSION PAGE IN BROWSER
# ══════════════════════════════════════════════════════════════════════

function Open-PortalSession {
    $portalUrl = "$HELPIT_API_BASE/helpit-agent/session/$SESSION_ID"
    Show-Status "Opening your HelpIT dashboard..." "Cyan"

    try { Start-Process $portalUrl } catch { }

    Show-Status "View live results at:" "Gray"
    Show-Status $portalUrl "Yellow"
    Write-Host ""
}


# ══════════════════════════════════════════════════════════════════════
# STEP 2: SCAN THE COMPUTER
# ══════════════════════════════════════════════════════════════════════

function Invoke-SystemScan {
    Show-Status "Scanning your computer..." "Yellow"

    # Update portal status
    Call-API -Method "PATCH" -Path "/api/agent/session/$SESSION_ID" -Body @{
        status = "scanning"
    } | Out-Null

    $scanData = @{}

    # ── OS Info ────────────────────────────────────────────────
    Show-Progress "System information" 5
    try {
        $os = Get-CimInstance Win32_OperatingSystem
        $cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
        $uptime = (Get-Date) - $os.LastBootUpTime
        $scanData["os"] = @{
            name         = $os.Caption
            version      = $os.Version
            build        = $os.BuildNumber
            architecture = $env:PROCESSOR_ARCHITECTURE
            uptime_hours = [math]::Round($uptime.TotalHours, 1)
        }
        $scanData["hardware"] = @{
            cpu              = $cpu.Name
            ram_total_gb     = [math]::Round($os.TotalVisibleMemorySize / 1MB, 1)
            ram_available_gb = [math]::Round($os.FreePhysicalMemory / 1MB, 1)
        }
    } catch {
        $scanData["os"] = @{ name = "Windows"; error = $_.Exception.Message }
    }

    # ── Disk Space ─────────────────────────────────────────────
    Show-Progress "Disk space" 15
    try {
        $drv = Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Used -ne $null } | Select-Object -First 1
        if ($drv) {
            $total = [math]::Round(($drv.Used + $drv.Free) / 1GB, 1)
            $free = [math]::Round($drv.Free / 1GB, 1)
            if (-not $scanData["hardware"]) { $scanData["hardware"] = @{} }
            $scanData["hardware"]["disk_total_gb"] = $total
            $scanData["hardware"]["disk_free_gb"] = $free
        }
    } catch { }

    # ── Security ───────────────────────────────────────────────
    Show-Progress "Security status" 25
    try {
        $defender = Get-MpComputerStatus -ErrorAction SilentlyContinue
        $firewall = (Get-NetFirewallProfile -ErrorAction SilentlyContinue | Where-Object { $_.Enabled -eq $true }).Count
        $scanData["security"] = @{
            antivirus        = if ($defender) { "Windows Defender" } else { "Unknown" }
            firewall_enabled = ($firewall -gt 0)
            real_time_on     = if ($defender) { $defender.RealTimeProtectionEnabled } else { $false }
        }
        try {
            $updateSession = New-Object -ComObject Microsoft.Update.Session -ErrorAction SilentlyContinue
            if ($updateSession) {
                $searcher = $updateSession.CreateUpdateSearcher()
                $pending = $searcher.Search("IsInstalled=0").Updates.Count
                $scanData["security"]["pending_updates"] = $pending
            }
        } catch { $scanData["security"]["pending_updates"] = -1 }
    } catch {
        $scanData["security"] = @{ antivirus = "Unknown" }
    }

    # ── Startup Programs ───────────────────────────────────────
    Show-Progress "Startup programs" 35
    try {
        $startupItems = @()
        $regUser = Get-ItemProperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -ErrorAction SilentlyContinue
        if ($regUser) {
            $regUser.PSObject.Properties | Where-Object { $_.Name -notlike "PS*" } | ForEach-Object {
                $startupItems += @{ name = $_.Name; enabled = $true; impact = "medium"; source = "registry_user" }
            }
        }
        $regMachine = Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" -ErrorAction SilentlyContinue
        if ($regMachine) {
            $regMachine.PSObject.Properties | Where-Object { $_.Name -notlike "PS*" } | ForEach-Object {
                $startupItems += @{ name = $_.Name; enabled = $true; impact = "medium"; source = "registry_machine" }
            }
        }
        try {
            $wmicStartup = Get-CimInstance Win32_StartupCommand -ErrorAction SilentlyContinue
            if ($wmicStartup) {
                foreach ($item in $wmicStartup) {
                    if ($startupItems.name -notcontains $item.Name) {
                        $startupItems += @{ name = $item.Name; enabled = $true; impact = "medium"; source = "wmi" }
                    }
                }
            }
        } catch { }
        $scanData["startup_programs"] = $startupItems
    } catch { $scanData["startup_programs"] = @() }

    # ── Running Processes ──────────────────────────────────────
    Show-Progress "Running processes" 50
    try {
        $procs = Get-Process | Sort-Object WorkingSet64 -Descending | Select-Object -First 30
        $scanData["running_processes"] = (Get-Process).Count
        $scanData["top_processes"] = @($procs | ForEach-Object {
            @{ name = $_.ProcessName; memory_mb = [math]::Round($_.WorkingSet64 / 1MB); cpu_sec = [math]::Round($_.CPU, 1) }
        })
    } catch { $scanData["running_processes"] = 0 }

    # ── Event Log Errors ───────────────────────────────────────
    Show-Progress "System event logs" 60
    try {
        $errors = Get-WinEvent -FilterHashtable @{
            LogName = 'System','Application'; Level = 1,2; StartTime = (Get-Date).AddDays(-7)
        } -MaxEvents 20 -ErrorAction SilentlyContinue
        $scanData["event_log_errors"] = @($errors | ForEach-Object {
            @{ source = $_.ProviderName; level = if ($_.Level -eq 1) { "Critical" } else { "Error" }
               message = $_.Message.Substring(0, [math]::Min($_.Message.Length, 200))
               timestamp = $_.TimeCreated.ToString("yyyy-MM-dd HH:mm:ss") }
        })
    } catch { $scanData["event_log_errors"] = @() }

    # ── Network ────────────────────────────────────────────────
    Show-Progress "Network configuration" 75
    try {
        $adapter = Get-NetAdapter | Where-Object { $_.Status -eq "Up" } | Select-Object -First 1
        $dns = (Get-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue).ServerAddresses
        $dnsWorking = $true
        try { [System.Net.Dns]::GetHostAddresses("www.google.com") | Out-Null } catch { $dnsWorking = $false }
        $scanData["network"] = @{ adapter = $adapter.Name; speed_mbps = $adapter.LinkSpeed; dns = $dns; dns_working = $dnsWorking }
    } catch { $scanData["network"] = @{ error = "Could not check" } }

    # ── Temp Files ─────────────────────────────────────────────
    Show-Progress "Temporary files" 85
    try {
        $tempSize = 0
        @($env:TEMP, "$env:LOCALAPPDATA\Temp", "$env:WINDIR\Temp") | ForEach-Object {
            if (Test-Path $_) {
                $size = (Get-ChildItem $_ -Recurse -File -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
                if ($size) { $tempSize += $size }
            }
        }
        $scanData["temp_files_gb"] = [math]::Round($tempSize / 1GB, 2)
    } catch { $scanData["temp_files_gb"] = 0 }

    # ── Installed Programs + Extensions ────────────────────────
    Show-Progress "Installed programs" 92
    try {
        $programs = Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" -ErrorAction SilentlyContinue
        $programs += Get-ItemProperty "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*" -ErrorAction SilentlyContinue
        $scanData["installed_programs_count"] = ($programs | Where-Object { $_.DisplayName }).Count
    } catch { $scanData["installed_programs_count"] = 0 }

    Show-Progress "Browser extensions" 97
    try {
        $extCount = 0
        $chromePath = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Extensions"
        $edgePath = "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Extensions"
        if (Test-Path $chromePath) { $extCount += (Get-ChildItem $chromePath -Directory -ErrorAction SilentlyContinue).Count }
        if (Test-Path $edgePath) { $extCount += (Get-ChildItem $edgePath -Directory -ErrorAction SilentlyContinue).Count }
        $scanData["browser_extensions"] = $extCount
    } catch { $scanData["browser_extensions"] = 0 }

    Show-Progress "Scan complete!" 100
    Write-Host ""

    return $scanData
}


# ══════════════════════════════════════════════════════════════════════
# STEP 3: SUBMIT SCAN DATA TO AI
# ══════════════════════════════════════════════════════════════════════

function Submit-ScanData {
    param([hashtable]$ScanData)

    Show-Status "Sending to AI for analysis..." "Yellow"

    $result = Call-API -Method "POST" -Path "/api/agent/scan" -Body @{
        session_token = $SESSION_TOKEN
        scan_data     = $ScanData
    }

    if ($result._error) {
        Show-Status "AI analysis failed: $($result.message)" "Red"
        return $null
    }

    Show-Status "AI analysis complete. Check your browser for results." "Green"
    return $result
}


# ══════════════════════════════════════════════════════════════════════
# STEP 4: WAIT FOR APPROVAL (customer approves on portal)
# ══════════════════════════════════════════════════════════════════════

function Wait-ForApproval {
    Show-Status "Waiting for you to approve fixes in the browser..." "Yellow"
    Show-Status "(You can minimize this window)" "DarkGray"

    $maxWait = 600
    $elapsed = 0

    while ($elapsed -lt $maxWait) {
        Start-Sleep -Seconds $POLL_INTERVAL
        $elapsed += $POLL_INTERVAL

        $session = Call-API -Method "GET" -Path "/api/agent/session/$SESSION_ID"
        if ($session._error) { continue }

        $status = $session.session.status

        if ($status -eq "fixing") {
            Show-Status "Fixes approved! Applying now..." "Green"
            return $session.session.fixes_approved
        }
        elseif ($status -eq "cancelled") {
            Show-Status "Session cancelled. No changes made." "Yellow"
            return $null
        }
        elseif ($status -eq "completed") {
            Show-Status "Session completed." "Green"
            return $null
        }
    }

    Show-Status "Timed out waiting for approval." "Red"
    return $null
}


# ══════════════════════════════════════════════════════════════════════
# STEP 5: APPLY FIXES
# ══════════════════════════════════════════════════════════════════════

function Invoke-ApprovedFixes {
    param([array]$Fixes)

    # Create restore point
    Show-Status "Creating safety restore point..." "Yellow"
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
    if ($isAdmin) {
        try {
            Enable-ComputerRestore -Drive "C:\" -ErrorAction SilentlyContinue
            $rpName = "HELPIT_$(Get-Date -Format 'yyyyMMdd_HHmm')"
            Checkpoint-Computer -Description $rpName -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
            Show-Status "Restore point: $rpName" "Green"
        } catch {
            Show-Status "Could not create restore point. Continuing safely." "Yellow"
        }
    } else {
        Show-Status "Tip: Run as Administrator for restore point protection." "DarkGray"
    }

    # Apply each fix
    $total = $Fixes.Count
    for ($i = 0; $i -lt $total; $i++) {
        $fix = $Fixes[$i]
        $num = $i + 1
        Show-Status "Fixing $num of $total : $($fix.title)..." "White"

        $result = "success"
        $errorDetails = $null

        try {
            $command = $fix.fix.command
            if ($command) {
                $output = Invoke-Expression $command 2>&1
                Show-Status "  Done." "Green"
            } else {
                Show-Status "  Noted in report." "Gray"
            }
        } catch {
            $result = "failed"
            $errorDetails = $_.Exception.Message
            Show-Status "  Failed: $errorDetails" "Red"
        }

        # Report result
        Call-API -Method "POST" -Path "/api/agent/fix-result" -Body @{
            session_token = $SESSION_TOKEN
            fix_id        = $fix.title
            result        = $result
            error_details = $errorDetails
        } | Out-Null
    }
}


# ══════════════════════════════════════════════════════════════════════
# STEP 6: CLEANUP AND EXIT
# ══════════════════════════════════════════════════════════════════════

function Complete-AndExit {
    Write-Host ""
    Show-Status "All done! Check your browser for the full report." "Green"
    Show-Status "This window will close in 10 seconds." "DarkGray"

    Start-Sleep -Seconds 10

    # Self-delete
    $scriptPath = $PSCommandPath
    if ($scriptPath -and (Test-Path $scriptPath)) {
        $cleanup = "$env:TEMP\helpit_cleanup.bat"
        "@echo off`nping 127.0.0.1 -n 4 >nul`ndel /f /q `"$scriptPath`"`ndel /f /q `"%~f0`"" |
            Out-File $cleanup -Encoding ASCII
        Start-Process cmd.exe -ArgumentList "/c `"$cleanup`"" -WindowStyle Hidden
    }
}


# ══════════════════════════════════════════════════════════════════════
# MAIN — Clean, simple, no login needed
# ══════════════════════════════════════════════════════════════════════

try {
    Show-Banner

    # 1. Open the portal session page in browser
    Open-PortalSession

    # 2. Scan the computer
    $scanData = Invoke-SystemScan

    # 3. Send to AI
    $analysis = Submit-ScanData -ScanData $scanData
    if (-not $analysis) {
        Call-API -Method "PATCH" -Path "/api/agent/session/$SESSION_ID" -Body @{
            status = "failed"; error_message = "AI analysis failed"
        } | Out-Null
        Show-Status "Could not analyze. Check your browser." "Red"
        Start-Sleep -Seconds 5
        exit 1
    }

    if ($analysis.analysis.issueCount -eq 0) {
        Show-Status "No issues found! Your computer is healthy." "Green"
        Complete-AndExit
        exit 0
    }

    # 4. Wait for approval (customer approves on portal)
    $approvedFixes = Wait-ForApproval
    if (-not $approvedFixes -or $approvedFixes.Count -eq 0) {
        Show-Status "No fixes approved." "Yellow"
        Start-Sleep -Seconds 5
        exit 0
    }

    # 5. Apply fixes
    Invoke-ApprovedFixes -Fixes $approvedFixes

    # 6. Done
    Complete-AndExit

} catch {
    Write-Host ""
    Show-Status "Error: $($_.Exception.Message)" "Red"
    Show-Status "No changes were made." "Yellow"
    Start-Sleep -Seconds 10
}
